version: '3.8'

services:
  app:
    image: shubhangi2607/simple-cloud-storage:latest
    ports:
      - "3001:3000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cloud-storage
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 